# run all micriservices in docker-compose
version: '3.7'

services:
  # Movie Service
  movie_service:
    build: ./movie_service
    # onnce the image is built, we can run the container
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./movie_service:/movie_servies
    ports:
      # map container port 8000 to host port 8000
      - 8000:8000
    # set environment variables
    environment:
      # - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
      - CONTAINER_TEST_MOVIE_SERVICE=1
  # cast service
  cast_service:
    build: ./cast_service
    command: uvicorn main:app --host 0.0.0.0 --port 8001
    volumes:
      - ./cast_service:/cast_services
    ports:
      - 8001:8001
    environment:
      # - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
      - CONTAINER_TEST_CAST_SERVICE=1
  
nginx:
    image: nginx:latest
    ports:
      - 8080:8080
    volumes:
      - ./nginx_microservice_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      -movie_service
      -cast_service
