version: '3.7'

services:
  movie_service:
    build: ./movie_service
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./movie_service:/movie_servies
    ports:
      - 8000:8000
    environment:
      - CONTAINER_TEST_MOVIE_SERVICE=1
      - DATABASE_URL=postgresql://postgres:mea4545Luda@127.0.0.1:5432/movies_microservice_db
  cast_service:
    build: ./cast_service
    command: uvicorn main:app --host 0.0.0.0 --port 8001
    volumes:
      - ./cast_service:/cast_services
    ports:
      - 8001:8001
    environment:
      - CONTAINER_TEST_CAST_SERVICE=1
      - DATABASE_URL=postgresql://postgres:mea4545Luda@127.0.0.1:5432/movies_microservice_db
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ./nginx_microservice_config.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - cast_service
  #     - movie_service
